name: sum

on:
  workflow_call:

    inputs:
      number1: 
        description: 'first number'
        type: number
        default: '0'
        required: true

      number2: 
        description: 'second number'
        type: number
        default: '0'
        required: true
jobs:
  add_number:
    runs-on: ubuntu-latest

    steps:
      - name: add
        id: sum
        run: echo "::set-output name=sum::$((${{inputs.number1}} + ${{inputs.number2}}))"

      - name: displaysum
        run: echo " the sum of ${{inputs.number1}} and ${{inputs.number2}} is ${{steps.sum.outputs.sum}}"
    
