name: test


on:
  workflow_dispatch: 

env:
  cloud: GCP

jobs:
  test_variables:
   runs-on: ubuntu-latest
   steps:
     - name: "check context cariables " 
       run: |
         echo " repo : ${{github.repository}}"
